# http://docs.travis-ci.com/user/build-configuration/

language: node_js

node_js:
  - '0.10'
  - '0.11'

before_install:
  - npm install -g gulp

install:
  - npm install

script:
  - gulp test
  - gulp ioviz.js
